name: Static Code Analysis - Checkov
on: [push]
jobs:
  checkov-job:
    runs-on: ubuntu-latest
    name: checkov-action
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          config_file: ./config.yaml
          # directory: ./terraform/
          # check: CKV_AWS_1 # optional: run only a specific check_id. can be comma separated list
          # skip_check: CKV_AWS_2 # optional: skip a specific check_id. can be comma separated list
          # quiet: true # optional: display only failed checks
          # soft_fail: true # optional: do not return an error code if there are failed checks
          # framework: terraform 
          # output_format: json 
          # download_external_modules: true # optional: download external terraform modules from public git repositories and terraform registry
