name: Static Code Analysis - Checkov
on: [push]
jobs:
  checkov-job:
    runs-on: ubuntu-latest
    name: checkov-action
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          config_file: ./terraform/config.yaml
          # directory: ./terraform/
          # download_external_modules: true 
          # framework: all 
          # output_format: cli 
          # quiet: true
          # soft_fail: true
          # compact: true
