name: yor
on:
  pull_request: 
jobs:
  yor-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - name: Update coverage
        run: |
          git config --local user.email "jonny.boniface@rootleveltech.com"
          git config --local user.name "Jonny Boniface"
      - name: Run yor action
        uses: bridgecrewio/yor-action@main
        with:
          directory: ./terraform/
          tag_groups: git
          # tag: git_modifiers,git_commit,git_repository,yor_trace
          # # skip_tags: git_modifiers,git_commit,git_repository
          log_level: DEBUG
          output_format: json
          commit_changes: YES

