name: yor
on:
  pull_request: 
jobs:
  yor-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run yor action
        uses: bridgecrewio/yor-action@main
        with:
          directory: ./terraform/
          log_level: DEBUG
          skip_tags: git_modifiers,git_commit,git_repository
          tag_groups: git
          tag: git_commit
          # tag_groups: git
          # output_format: json